version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  win: circleci/windows@4.1.1

jobs:
  ubuntu_build:
    docker:
      - image: cimg/clojure:1.11.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run:
          name: Tools Versions
          command: |
            java -version
            clojure --version
            lein --version
            node --version
            google-chrome --version
            chromedriver --version
            firefox --version
            geckodriver --version

  macos_build:
    macos:
      xcode: "12.5.1"
    steps:
      - browser-tools/install-browser-tools
      - run:
          name: Install Leiningen
          command: brew install leiningen
      - checkout
      - run:
          name: Tools Versions
          command: |
            java -version
            lein --version
            node --version
            google-chrome --version
            chromedriver --version
            firefox --version
            geckodriver --version

  win_build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run:
          name: What's here?
          command: |
            tree $HOME
            echo $Env:Path
      - run:
          name: Install Babashka
          command: |
            mkdir -p c:\tools\babashka
            [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable('Path', 'Machine') + ";c:\tools\babashka", "Machine")
            (New-Object System.Net.WebClient).DownloadFile('https://github.com/babashka/babashka/releases/download/v0.8.2/babashka-0.8.2-windows-amd64.zip','c:\tools\babashka\bb.zip')
            Expand-Archive 'c:\tools\babashka\bb.zip' -DestinationPath 'c:\tools\babashka'
      - checkout
      - run:
          name: What da path now?
          command: echo $Env:Path
      - run: bb --version
      - run: java -version
      - run: node --version

workflows:
  run-jobs:
    jobs:
      #- ubuntu_build
      #- macos_build
      - win_build
