version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  windows: circleci/windows@4.1.1

jobs:
  ubuntu_build:
    docker:
      - image: cimg/clojure:1.11.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run:
          name: Tools Versions
          command: |
            java -version
            clojure --version
            lein --version
            node --version
            google-chrome --version
            chromedriver --version
            firefox --version
            geckodriver --version

  macos_build:
    macos:
      xcode: "12.5.1"
    steps:
      - browser-tools/install-browser-tools
      - run:
          name: Install Leiningen
          command: brew install leiningen
      - checkout
      - run:
          name: Tools Versions
          command: |
            java -version
            lein --version
            node --version
            google-chrome --version
            chromedriver --version
            firefox --version
            geckodriver --version

  win_build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  run-jobs:
    jobs:
      - ubuntu_build
      - macos_build
