version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          clojure --version
          node --version
          google-chrome --version
          chromedriver --version
          firefox --version
          geckodriver --version
