name: publish
on:
  push:
    tags:
      - 'v\d+.*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        run: echo "Pretending to publish"
