name: release
on:
  workflow_dipatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [all-tests]

    steps:
    - name: Pretend we are releasing
      run: echo Releasing
