name: release
on:
  push:
    tags:
      - 'v\d+.*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  deploy:
    environment: release
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clojure deps cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@9.3
      with:
        lein: 'latest'
        bb: 'latest'

    - name: Tools Versions
      run: |
        echo "bb --version"
        bb --version
        echo "lein --version"
        lein --version

    - name: Download Clojure Dependencies
      run: lein deps

    - name: Deploy to clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: bb -ci-clojars-deploy

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bb -ci-github-create-release
